/********************************************************************
* GenSimPrimaryEventGeneratorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GenSimPrimaryEventGeneratorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGenSimPrimaryEventGeneratorDict();
extern void G__cpp_setup_inheritanceGenSimPrimaryEventGeneratorDict();
extern void G__cpp_setup_typetableGenSimPrimaryEventGeneratorDict();
extern void G__cpp_setup_memvarGenSimPrimaryEventGeneratorDict();
extern void G__cpp_setup_globalGenSimPrimaryEventGeneratorDict();
extern void G__cpp_setup_memfuncGenSimPrimaryEventGeneratorDict();
extern void G__cpp_setup_funcGenSimPrimaryEventGeneratorDict();
extern void G__set_cpp_environmentGenSimPrimaryEventGeneratorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/hlee/G4/modify6/GenSim/include/GenSimPrimaryEventGenerator.hh"
