/********************************************************************
* GenSimMainEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error GenSimMainEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGenSimMainEventDict();
extern void G__cpp_setup_inheritanceGenSimMainEventDict();
extern void G__cpp_setup_typetableGenSimMainEventDict();
extern void G__cpp_setup_memvarGenSimMainEventDict();
extern void G__cpp_setup_globalGenSimMainEventDict();
extern void G__cpp_setup_memfuncGenSimMainEventDict();
extern void G__cpp_setup_funcGenSimMainEventDict();
extern void G__set_cpp_environmentGenSimMainEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/hlee/G4/modify6/GenSim/include/GenSimMainEvent.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GenSimMainEventDictLN_TClass;
extern G__linked_taginfo G__GenSimMainEventDictLN_TBuffer;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMemberInspector;
extern G__linked_taginfo G__GenSimMainEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__GenSimMainEventDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GenSimMainEventDictLN_GenSimPrimaryEvent;
extern G__linked_taginfo G__GenSimMainEventDictLN_GenSimADetEvent;
extern G__linked_taginfo G__GenSimMainEventDictLN_GenSimMainEvent;

/* STUB derived class for protected member access */
