//
// File generated by /pkg/root_v5.34.23/bin/rootcint at Tue Nov 13 13:04:55 2018

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME GenSimMainEventDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GenSimMainEventDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GenSimMainEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_GenSimMainEvent(void *p = 0);
   static void *newArray_GenSimMainEvent(Long_t size, void *p);
   static void delete_GenSimMainEvent(void *p);
   static void deleteArray_GenSimMainEvent(void *p);
   static void destruct_GenSimMainEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GenSimMainEvent*)
   {
      ::GenSimMainEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GenSimMainEvent >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GenSimMainEvent", ::GenSimMainEvent::Class_Version(), "/home/hlee/G4/modify6/GenSim/include/GenSimMainEvent.hh", 19,
                  typeid(::GenSimMainEvent), DefineBehavior(ptr, ptr),
                  &::GenSimMainEvent::Dictionary, isa_proxy, 4,
                  sizeof(::GenSimMainEvent) );
      instance.SetNew(&new_GenSimMainEvent);
      instance.SetNewArray(&newArray_GenSimMainEvent);
      instance.SetDelete(&delete_GenSimMainEvent);
      instance.SetDeleteArray(&deleteArray_GenSimMainEvent);
      instance.SetDestructor(&destruct_GenSimMainEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GenSimMainEvent*)
   {
      return GenerateInitInstanceLocal((::GenSimMainEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GenSimMainEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr GenSimMainEvent::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *GenSimMainEvent::Class_Name()
{
   return "GenSimMainEvent";
}

//______________________________________________________________________________
const char *GenSimMainEvent::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GenSimMainEvent*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GenSimMainEvent::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GenSimMainEvent*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GenSimMainEvent::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GenSimMainEvent*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GenSimMainEvent::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GenSimMainEvent*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void GenSimMainEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class GenSimMainEvent.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(GenSimMainEvent::Class(),this);
   } else {
      R__b.WriteClassBuffer(GenSimMainEvent::Class(),this);
   }
}

//______________________________________________________________________________
void GenSimMainEvent::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class GenSimMainEvent.
      TClass *R__cl = ::GenSimMainEvent::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "GenSimPrimEvent", &GenSimPrimEvent);
      R__insp.InspectMember(GenSimPrimEvent, "GenSimPrimEvent.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "GenSimEvent", &GenSimEvent);
      R__insp.InspectMember(GenSimEvent, "GenSimEvent.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrackVertexPositionX", &TrackVertexPositionX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrackVertexPositionY", &TrackVertexPositionY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrackVertexPositionZ", &TrackVertexPositionZ);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TrackVertexTotalKineticEnergy", &TrackVertexTotalKineticEnergy);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_GenSimMainEvent(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::GenSimMainEvent : new ::GenSimMainEvent;
   }
   static void *newArray_GenSimMainEvent(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::GenSimMainEvent[nElements] : new ::GenSimMainEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_GenSimMainEvent(void *p) {
      delete ((::GenSimMainEvent*)p);
   }
   static void deleteArray_GenSimMainEvent(void *p) {
      delete [] ((::GenSimMainEvent*)p);
   }
   static void destruct_GenSimMainEvent(void *p) {
      typedef ::GenSimMainEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GenSimMainEvent

/********************************************************
* GenSimMainEventDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGenSimMainEventDict();

extern "C" void G__set_cpp_environmentGenSimMainEventDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/home/hlee/G4/modify6/GenSim/include/GenSimMainEvent.hh");
  G__cpp_reset_tagtableGenSimMainEventDict();
}
#include <new>
extern "C" int G__cpp_dllrevGenSimMainEventDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GenSimMainEvent */
static int G__GenSimMainEventDict_1017_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GenSimMainEvent*) G__getstructoffset())->SetTrackVertexPositionX((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GenSimMainEvent*) G__getstructoffset())->SetTrackVertexPositionY((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GenSimMainEvent*) G__getstructoffset())->SetTrackVertexPositionZ((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GenSimMainEvent*) G__getstructoffset())->Initialize();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GenSimMainEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GenSimMainEvent[n];
     } else {
       p = new((void*) gvp) GenSimMainEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GenSimMainEvent;
     } else {
       p = new((void*) gvp) GenSimMainEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GenSimMainEventDictLN_GenSimMainEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GenSimMainEvent::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GenSimMainEvent::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GenSimMainEvent::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GenSimMainEvent::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const GenSimMainEvent*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GenSimMainEvent*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GenSimMainEvent*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GenSimMainEvent*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GenSimMainEvent::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GenSimMainEvent::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GenSimMainEvent::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GenSimMainEventDict_1017_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GenSimMainEvent::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GenSimMainEventDict_1017_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   GenSimMainEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new GenSimMainEvent(*(GenSimMainEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GenSimMainEventDictLN_GenSimMainEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GenSimMainEvent G__TGenSimMainEvent;
static int G__GenSimMainEventDict_1017_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GenSimMainEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GenSimMainEvent*) (soff+(sizeof(GenSimMainEvent)*i)))->~G__TGenSimMainEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GenSimMainEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GenSimMainEvent*) (soff))->~G__TGenSimMainEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__GenSimMainEventDict_1017_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GenSimMainEvent* dest = (GenSimMainEvent*) G__getstructoffset();
   *dest = *(GenSimMainEvent*) libp->para[0].ref;
   const GenSimMainEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GenSimMainEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGenSimMainEventDict {
 public:
  G__Sizep2memfuncGenSimMainEventDict(): p(&G__Sizep2memfuncGenSimMainEventDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGenSimMainEventDict::*p)();
};

size_t G__get_sizep2memfuncGenSimMainEventDict()
{
  G__Sizep2memfuncGenSimMainEventDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGenSimMainEventDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGenSimMainEventDict() {

   /* Setting up typedef entry */
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__GenSimMainEventDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GenSimMainEvent */
static void G__setup_memvarGenSimMainEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GenSimMainEventDictLN_GenSimMainEvent));
   { GenSimMainEvent *p; p=(GenSimMainEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->GenSimPrimEvent)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__GenSimMainEventDictLN_GenSimPrimaryEvent),-1,-1,1,"GenSimPrimEvent=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->GenSimEvent)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__GenSimMainEventDictLN_GenSimADetEvent),-1,-1,1,"GenSimEvent=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrackVertexPositionX)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"TrackVertexPositionX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrackVertexPositionY)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"TrackVertexPositionY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrackVertexPositionZ)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"TrackVertexPositionZ=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TrackVertexTotalKineticEnergy)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"TrackVertexTotalKineticEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GenSimMainEventDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGenSimMainEventDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGenSimMainEvent(void) {
   /* GenSimMainEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GenSimMainEventDictLN_GenSimMainEvent));
   G__memfunc_setup("SetTrackVertexPositionX",2380,G__GenSimMainEventDict_1017_0_1, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTrackVertexPositionY",2381,G__GenSimMainEventDict_1017_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetTrackVertexPositionZ",2382,G__GenSimMainEventDict_1017_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - val", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Initialize",1042,G__GenSimMainEventDict_1017_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GenSimMainEvent",1482,G__GenSimMainEventDict_1017_0_5, 105, G__get_linked_tagnum(&G__GenSimMainEventDictLN_GenSimMainEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__GenSimMainEventDict_1017_0_6, 85, G__get_linked_tagnum(&G__GenSimMainEventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GenSimMainEvent::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GenSimMainEventDict_1017_0_7, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GenSimMainEvent::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GenSimMainEventDict_1017_0_8, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GenSimMainEvent::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GenSimMainEventDict_1017_0_9, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GenSimMainEvent::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__GenSimMainEventDict_1017_0_10, 85, G__get_linked_tagnum(&G__GenSimMainEventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__GenSimMainEventDict_1017_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__GenSimMainEventDict_1017_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GenSimMainEventDict_1017_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GenSimMainEventDict_1017_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GenSimMainEvent::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GenSimMainEventDict_1017_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GenSimMainEvent::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GenSimMainEventDict_1017_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GenSimMainEvent::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GenSimMainEventDict_1017_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GenSimMainEvent::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("GenSimMainEvent", 1482, G__GenSimMainEventDict_1017_0_18, (int) ('i'), G__get_linked_tagnum(&G__GenSimMainEventDictLN_GenSimMainEvent), -1, 0, 1, 1, 1, 0, "u 'GenSimMainEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GenSimMainEvent", 1608, G__GenSimMainEventDict_1017_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__GenSimMainEventDict_1017_0_20, (int) ('u'), G__get_linked_tagnum(&G__GenSimMainEventDictLN_GenSimMainEvent), -1, 1, 1, 1, 1, 0, "u 'GenSimMainEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGenSimMainEventDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGenSimMainEventDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {
}

static void G__cpp_setup_func36() {
}

static void G__cpp_setup_func37() {
}

static void G__cpp_setup_func38() {
}

static void G__cpp_setup_func39() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGenSimMainEventDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
  G__cpp_setup_func36();
  G__cpp_setup_func37();
  G__cpp_setup_func38();
  G__cpp_setup_func39();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GenSimMainEventDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_GenSimPrimaryEvent = { "GenSimPrimaryEvent" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_GenSimADetEvent = { "GenSimADetEvent" , 99 , -1 };
G__linked_taginfo G__GenSimMainEventDictLN_GenSimMainEvent = { "GenSimMainEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGenSimMainEventDict() {
  G__GenSimMainEventDictLN_TClass.tagnum = -1 ;
  G__GenSimMainEventDictLN_TBuffer.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMemberInspector.tagnum = -1 ;
  G__GenSimMainEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__GenSimMainEventDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GenSimMainEventDictLN_GenSimPrimaryEvent.tagnum = -1 ;
  G__GenSimMainEventDictLN_GenSimADetEvent.tagnum = -1 ;
  G__GenSimMainEventDictLN_GenSimMainEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGenSimMainEventDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_GenSimPrimaryEvent);
   G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_GenSimADetEvent);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GenSimMainEventDictLN_GenSimMainEvent),sizeof(GenSimMainEvent),-1,263424,(char*)NULL,G__setup_memvarGenSimMainEvent,G__setup_memfuncGenSimMainEvent);
}
extern "C" void G__cpp_setupGenSimMainEventDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGenSimMainEventDict()");
  G__set_cpp_environmentGenSimMainEventDict();
  G__cpp_setup_tagtableGenSimMainEventDict();

  G__cpp_setup_inheritanceGenSimMainEventDict();

  G__cpp_setup_typetableGenSimMainEventDict();

  G__cpp_setup_memvarGenSimMainEventDict();

  G__cpp_setup_memfuncGenSimMainEventDict();
  G__cpp_setup_globalGenSimMainEventDict();
  G__cpp_setup_funcGenSimMainEventDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGenSimMainEventDict();
  return;
}
class G__cpp_setup_initGenSimMainEventDict {
  public:
    G__cpp_setup_initGenSimMainEventDict() { G__add_setup_func("GenSimMainEventDict",(G__incsetup)(&G__cpp_setupGenSimMainEventDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGenSimMainEventDict() { G__remove_setup_func("GenSimMainEventDict"); }
};
G__cpp_setup_initGenSimMainEventDict G__cpp_setup_initializerGenSimMainEventDict;

